import { GetStaticProps, NextPage } from "next";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Head from "next/head";
import { IPost } from "../app/interfaces/pages/Home";
import Post from "../app/components/Post";

interface HomePropsTypes {
  posts: IPost[];
}

const Home: NextPage<HomePropsTypes> = ({ posts }) => {
  return (
    <div className="container">
      <Head>
        <title>Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="posts">
        {posts?.length && posts.map((post) => <Post key={post?.frontMatter?.title} post={post} />)}
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const files = fs.readdirSync(path.join("posts"));
  const posts = files.map((filename) => {
    const markdownWithMeta = fs.readFileSync(path.join("posts", filename), "utf-8");
    const { data: frontMatter } = matter(markdownWithMeta);
    const slug = filename.replace(".md", "");
    return { slug, frontMatter } as IPost;
  });
  return {
    props: {
      posts
    }
  };
};
